name: asteroids
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
    
  flame: ^1.34.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/spaceship/spaceship.png
   - assets/images/spaceship/spaceship_dash.png

   - assets/images/projectiles/plasma_bolt.png

   - assets/images/asteroids/asteroid_0.png
   - assets/images/asteroids/asteroid_1.png
   - assets/images/asteroids/asteroid_2.png
   - assets/images/asteroids/asteroid_3.png
   - assets/images/asteroids/asteroid_4.png
   - assets/images/asteroids/asteroid_5.png
  